In [18]:
%reload_ext autoreload
%autoreload 2

In [19]:
import perceval as pcvl
import lo_reservoir as lrs

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Load the data

In [20]:
m = 5
data_matrix = lrs.load_data_into_matrix("wind_data_fr_2021.csv", m)

# Take a subset of datapoints
data_matrix = data_matrix[:1000, :]


t_max = data_matrix.shape[0]
print("m = ", m)
print("t_max = ", t_max)

m =  5
t_max =  1000


# Generate expectation matrix (t_max, m)

In [21]:
simulator = lrs.PhotonicReservoirSimulator(m, t_max, overlapping=True)

# generate the layers
_ = simulator.set_circuit_with_stored_layers()

Generating layers: 100%|██████████| 1000/1000 [00:01<00:00, 767.69it/s]


In [22]:
input_state = pcvl.BasicState([3]*(m-2) + [0]*2)
expectations_matrix = simulator.sequential_expectation_calculation(data_matrix, input_state)

Processing time steps: 100%|██████████| 1000/1000 [02:38<00:00,  6.30it/s]


In [24]:
print("expectations_matrix.shape = ", np.array(expectations_matrix).shape)

expectations_matrix.shape =  (1000, 5)


In [3]:
m = 6 # max nb of modes 
t = 100 # need to adapt to time series length

simulator = lrs.PhotonicReservoirSimulator(m, t, overlapping=True)
data = simulator.generate_rndm_param_matrix()
simulator.set_circuit_parameters(data)
input_state = pcvl.BasicState([3]*(m-2) + [0]*2)
expectation_values = simulator.calculate_mode_expectations(input_state)
print("Expectation values for each mode:", expectation_values)

AttributeError: 'PhotonicReservoirSimulator' object has no attribute 'circuit'

In [5]:
# import a csv file
df = pd.read_csv("wind_data_fr_2021.csv", sep=";")
# remove the first column

# make a numpy array out of the dataframe
da = df.to_numpy()
# reduce the scale of the data
data_scaled_down = da / max(da)

In [6]:
print(data_scaled_down)
print(data_scaled_down.shape)

[[0.06232918]
 [0.1079928 ]
 [0.10765949]
 ...
 [0.22838477]
 [0.21725218]
 [0.21018599]]
(17520, 1)


In [7]:
# function to create new colums with the same data
def new_matrix(data, m):
    n = (m-1)*5
    new_data = np.zeros((data.shape[0], data.shape[1]*n))
    for i in range(n):
        new_data[:, i*data.shape[1]:(i+1)*data.shape[1]] = data
    return new_data

In [8]:
data_new_columns = new_matrix(data_scaled_down, 5)

In [9]:
print(data_new_columns)
print(data_new_columns.shape)

[[0.06232918 0.06232918 0.06232918 ... 0.06232918 0.06232918 0.06232918]
 [0.1079928  0.1079928  0.1079928  ... 0.1079928  0.1079928  0.1079928 ]
 [0.10765949 0.10765949 0.10765949 ... 0.10765949 0.10765949 0.10765949]
 ...
 [0.22838477 0.22838477 0.22838477 ... 0.22838477 0.22838477 0.22838477]
 [0.21725218 0.21725218 0.21725218 ... 0.21725218 0.21725218 0.21725218]
 [0.21018599 0.21018599 0.21018599 ... 0.21018599 0.21018599 0.21018599]]
(17520, 20)


In [25]:
m = 5 # max nb of modes 
t = len(data_new_columns[:1000]) # need to adapt to time series length

simulator = lrs.PhotonicReservoirSimulator(m, t, overlapping=True)
simulator.set_circuit_parameters(data_new_columns[:1000])
input_state = pcvl.BasicState([3]*(m-2) + [0]*2)
expectation_values = simulator.calculate_mode_expectations(input_state)
print("Expectation values for each mode:", expectation_values)

Expectation values for each mode: [2.0834143973411376, 2.5752346334633582, 0.4995991375986157, 2.759684465139715, 1.082067366457272]
